# See: https://circleci.com/docs/2.0/language-python/

version: 2
jobs:

  build-docs:
    working_directory: ~/repo
    docker:
      - image: cimg/python:3.9

    steps:
      - checkout

      - run:
          name: Install Python dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            python -m pip install --upgrade pip wheel setuptools
            python -m pip install -r requirements.txt

      - run:
          name: Build site
          no_output_timeout: 30m
          command: |
            source venv/bin/activate
            # n = nitpicky (broken links), W = warnings as errors,
            # T = full tracebacks, keep-going = run to completion even with errors
            make SPHINXOPTS="-nWT --keep-going" html

      - store_artifacts:
          path: build/html
